"""baseline

Revision ID: c6a6d2b2ab62
Revises: 
Create Date: 2026-02-27 16:29:45.545990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a6d2b2ab62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_summaries', 'summary_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('conversation_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_summaries_conversation_id'), table_name='conversation_summaries')
    op.alter_column('conversations', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_conversations_active_presentation'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.alter_column('messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'intent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('messages', 'is_in_working_memory',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_working_memory'), table_name='messages', postgresql_where='(is_in_working_memory = true)')
    op.drop_index(op.f('idx_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('presentation_pages', 'html_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('presentation_pages', 'page_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('presentation_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_presentation_pages_number'), table_name='presentation_pages')
    op.drop_index(op.f('idx_presentation_pages_presentation_id'), table_name='presentation_pages')
    op.drop_constraint(op.f('presentation_pages_presentation_id_page_number_key'), 'presentation_pages', type_='unique')
    op.create_unique_constraint('uq_presentation_page_number', 'presentation_pages', ['presentation_id', 'page_number'])
    op.alter_column('presentation_version_pages', 'html_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('presentation_version_pages', 'page_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_version_pages_number'), table_name='presentation_version_pages')
    op.drop_index(op.f('idx_version_pages_version_id'), table_name='presentation_version_pages')
    op.drop_constraint(op.f('presentation_version_pages_version_id_page_number_key'), 'presentation_version_pages', type_='unique')
    op.create_unique_constraint('uq_version_page_number', 'presentation_version_pages', ['version_id', 'page_number'])
    op.alter_column('presentation_versions', 'user_request',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('presentation_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_presentation_versions_combo'), table_name='presentation_versions')
    op.drop_index(op.f('idx_presentation_versions_presentation_id'), table_name='presentation_versions')
    op.drop_constraint(op.f('presentation_versions_presentation_id_version_key'), 'presentation_versions', type_='unique')
    op.create_unique_constraint('uq_presentation_version', 'presentation_versions', ['presentation_id', 'version'])
    op.alter_column('presentations', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('presentations', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('presentations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('presentations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_presentations_conversation_id'), table_name='presentations')
    op.drop_index(op.f('idx_presentations_created_at'), table_name='presentations')
    op.drop_index(op.f('idx_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_index(op.f('idx_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('idx_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_constraint(op.f('token_blacklist_token_jti_key'), 'token_blacklist', type_='unique')
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token_jti'), 'token_blacklist', ['token_jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.alter_column('user_facts', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_facts', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_facts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_facts_user_id'), table_name='user_facts')
    op.drop_constraint(op.f('user_facts_user_id_key_key'), 'user_facts', type_='unique')
    op.create_unique_constraint('uq_user_fact_key', 'user_facts', ['user_id', 'key'])
    op.alter_column('users', 'providers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("ARRAY['email'::text]"))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'providers',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("ARRAY['email'::text]"))
    op.drop_constraint('uq_user_fact_key', 'user_facts', type_='unique')
    op.create_unique_constraint(op.f('user_facts_user_id_key_key'), 'user_facts', ['user_id', 'key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_facts_user_id'), 'user_facts', ['user_id'], unique=False)
    op.alter_column('user_facts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_facts', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_facts', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.create_unique_constraint(op.f('token_blacklist_token_jti_key'), 'token_blacklist', ['token_jti'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('idx_token_blacklist_jti'), 'token_blacklist', ['token_jti'], unique=False)
    op.create_index(op.f('idx_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('idx_presentations_created_at'), 'presentations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_presentations_conversation_id'), 'presentations', ['conversation_id'], unique=False)
    op.alter_column('presentations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('presentations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('presentations', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('presentations', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_presentation_version', 'presentation_versions', type_='unique')
    op.create_unique_constraint(op.f('presentation_versions_presentation_id_version_key'), 'presentation_versions', ['presentation_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_presentation_versions_presentation_id'), 'presentation_versions', ['presentation_id'], unique=False)
    op.create_index(op.f('idx_presentation_versions_combo'), 'presentation_versions', ['presentation_id', 'version'], unique=False)
    op.alter_column('presentation_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('presentation_versions', 'user_request',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_version_page_number', 'presentation_version_pages', type_='unique')
    op.create_unique_constraint(op.f('presentation_version_pages_version_id_page_number_key'), 'presentation_version_pages', ['version_id', 'page_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_version_pages_version_id'), 'presentation_version_pages', ['version_id'], unique=False)
    op.create_index(op.f('idx_version_pages_number'), 'presentation_version_pages', ['version_id', 'page_number'], unique=False)
    op.alter_column('presentation_version_pages', 'page_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('presentation_version_pages', 'html_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_presentation_page_number', 'presentation_pages', type_='unique')
    op.create_unique_constraint(op.f('presentation_pages_presentation_id_page_number_key'), 'presentation_pages', ['presentation_id', 'page_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_presentation_pages_presentation_id'), 'presentation_pages', ['presentation_id'], unique=False)
    op.create_index(op.f('idx_presentation_pages_number'), 'presentation_pages', ['presentation_id', 'page_number'], unique=False)
    op.alter_column('presentation_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('presentation_pages', 'page_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('presentation_pages', 'html_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('idx_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('idx_messages_working_memory'), 'messages', ['conversation_id', 'is_in_working_memory', 'created_at'], unique=False, postgresql_where='(is_in_working_memory = true)')
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'is_in_working_memory',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('messages', 'intent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_conversations_active_presentation'), 'conversations', ['active_presentation_id'], unique=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.alter_column('conversation_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_summaries', 'summary_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
